version: 2.1
jobs:
  test:
    docker:
      - image: cirrusci/flutter:v1.7.8-hotfix.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: flutter test --coverage
      - run: bash <(curl -s https://codecov.io/bash)
  lint:
    docker:
      - image: cirrusci/flutter:v1.7.8-hotfix.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: flutter analyze
  format_check:
    docker:
      - image: cirrusci/flutter:v1.7.8-hotfix.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: flutter format --dry-run --set-exit-if-changed .
workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
      - format_check
